import {
  BarChart3,
  CheckSquare,
  Clock3,
  Gauge,
  GitBranch,
  Network,
  SearchCode,
  Settings2,
  TerminalSquare,
  TriangleAlert,
  UsersRound,
} from "lucide-react";

export const navigation = [
  {
    to: "/dashboard",
    icon: Gauge,
    label: "Overview",
    group: "Workspace",
    permission: "agent:chat",
  },
  {
    to: "/chat",
    icon: TerminalSquare,
    label: "Agent chat",
    group: "Workspace",
    permission: "agent:chat",
  },
  {
    to: "/multi-agent",
    icon: Network,
    label: "Agent orchestration",
    group: "Workspace",
    permission: "agents:orchestrate",
  },
  {
    to: "/diagnosis",
    icon: SearchCode,
    label: "CI/CD assistant",
    group: "Delivery",
    permission: "cicd:generate",
  },
  {
    to: "/repository-setup",
    icon: GitBranch,
    label: "Repositories",
    group: "Delivery",
    permission: "repositories:write",
  },
  {
    to: "/workflow-failures",
    icon: TriangleAlert,
    label: "Workflow failures",
    group: "Delivery",
    permission: "workflow_failures:read",
  },
  {
    to: "/approvals",
    icon: CheckSquare,
    label: "Approvals",
    group: "Governance",
    permission: "approvals:read",
  },
  {
    to: "/executions",
    icon: Clock3,
    label: "Audit log",
    group: "Governance",
    permission: "executions:read",
  },
  {
    to: "/evaluation",
    icon: BarChart3,
    label: "Evaluation",
    group: "Governance",
    permission: "metrics:read",
  },
  {
    to: "/users",
    icon: UsersRound,
    label: "Users & roles",
    group: "Manage",
    permission: "users:manage",
    webOnly: true,
  },
  {
    to: "/settings",
    icon: Settings2,
    label: "Settings",
    group: "Manage",
    permission: "agent:chat",
  },
];
